### ISSUE TITLE
Support for additional action arguments

### ISSUE THREAD

**Issue by udnisap** [rackt/react-router-redux#187]
I was using this for a while and thought this might be a quick implementation of router params. 
This is just passing the params to the reducer not via URL but via action itself. 

at https://github.com/rackt/redux-simple-router/blob/master/src/index.js#L8

if we replace
```javascript
function transition(method) {
  return arg => ({
    type: TRANSITION,
    method, arg
  })
}
```
with 
```javascript
function transition(method) {
  return (arg, data) => ({
    type: TRANSITION,
    method, arg, data
  })
}
```

we can do something link 
```javascript
import { routeActions } from 'redux-simple-router'
routeActions.push('login', 'custom data');
```

**Comment by udnisap** [comment]
looks like the transition is an internal event. is there a way to add things to location update event?

**Comment by udnisap** [comment]
params passed to `transition.push` will be the sent to `history` so we can use router params there.

**Comment by timdorr** [comment]
It might be better like this:
```js
function transition(method) {
  return ...arg => ({
    type: TRANSITION,
    method, args
  })
}
```
Then you can pass in an unlimited number of arguments, not just 1 or 2.

**Comment by timdorr** [comment]
This would make a great PR! :wink:

**Comment by udnisap** [comment]
But `TRANSITION` events are handled by the `reduxRouterMiddleware`. Only the `UPDATELOCATION` is passed to reducer. I was able to do this with 
`transition('push')({pathname: 'login' , state: somedata})` 
when dispatching and 
`action.location.state` in `reducer`

**Comment by timdorr** [comment]
Yes, that is correct. You should use the state property to store extra data about your location.
