### ISSUE TITLE
Dev Tools reset wipes out location state

### ISSUE THREAD

**Issue by srph** [rackt/react-router-redux#207]
I'm not sure if this is a bug or an issue with my code. Let me know if I'm submitting this to the wrong place.

Whether this was intended or not, please let me know.

## Behavior 
The state.routing.location key loses its value when the state is reset.

## Demo
https://github.com/chirigarikku/redux-simple-router-2-reset-state-bug

![preview](https://github.com/chirigarikku/redux-simple-router-2-reset-state-bug/raw/master/preview.gif)

**Comment by jasonh42** [comment]
Getting this issue as well. Using Redux DevTools, if you load a page, click "Reset", go between between pages, then try to replay the route changes, you get:

Uncaught TypeError: Cannot read property 'action' of undefined

If you don't Reset the state, then no issue occurs during replay. I wasn't getting this issue in 1.x.

**Comment by timdorr** [comment]
Looks like we need to reapply something like #6. It should [go here](https://github.com/gaearon/redux-devtools/blob/72cd8d050509b416fb3d65531978f5bd301c0cff/src/instrument.js#L168-L178). Anyone want to try their hand at a PR?

**Comment by srph** [comment]
i'll attempt

**Comment by srph** [comment]
looks like we'll need to parse the queries as well. 

what i got so far:

```es6
var initialState = typeof window === undefined ? {} : {
  location: {
    pathname: location.hash ? location.hash.substr(1) : '',
    search: (location.search ? ('?' + location.search) : ''),
    hash: '',
    action: '',
    key: '',
    query: qs.parse(location.query.replace(/\+/g, '%20'))
  }
};
```

**Comment by srph** [comment]
Can anyone point out if the <strike>solution</strike> hack I've thought of is valid?

**Comment by jlongster** [comment]
This is inherit in how this works -- we need to read the location first from `history`. What is actually throwing the error, is it something inside this library? I suppose user code is running with this default state. Maybe we should set the initial location to a blank object like `{ pathname: '' }` instead?

**Comment by vga-** [comment]
I couldn't get it to work by setting the initial state to a blank object.

Following @timdorr's suggestion, I've set the initial state to the window's location, string, and hash as follows:

```javascript
const initialState = typeof window === undefined ? {} : {
  location: {
    pathname: window.location.pathname,
    search: window.location.search,
    hash: window.location.hash
  }
};
```

This has worked so far in my few tests. It seems to mimic the fix for this issue when it occurred earlier on. Rather than setting the path to the concatenation of the window.location pathname, search, and hash, it sets the location object appropriately.

**Comment by jlongster** [comment]
@vga- we used to do something like that, but it doesn't work reliably. We want the initial location from the router, because the actual URL location is abstracted away. If you are using HashHistory your code breaks.

**Comment by jlongster** [comment]
I don't see what could be wrong with setting the initial location to a blank object. You will have to replay the first action to actually set the URL, yes, but that is *exactly* what is happening when the app loads.

**Comment by timdorr** [comment]
It's loosely related to #193. When the middleware is created, it gets the location via `history.listen`, which should return what that initial value is. 

I think it should be safe to set the `initialState` for the reducer at that time. But this still is really tricky to test. I'm going to add a Redux Dev Tools-enabled example so we can tool around with this stuff at little easier.

**Comment by timdorr** [comment]
Nevermind. I didn't know the basic example already had them :smile:

**Comment by srph** [comment]
Thanks <3
