### ISSUE TITLE
how todo redux-router validation of url and replace query param from any reducer?

### ISSUE THREAD

**Issue by stepancar** [rackt/react-router-redux#236]
I want to handle url changes in store of my page. Is it possible?

**Comment by timdorr** [comment]
You can make your own route reducer, if you'd like to.

**Comment by stepancar** [comment]
@timdorr could you provide any example, please?

**Comment by tsutigumo** [comment]
+1 example of url params handling would be really helpful!

**Comment by rnfomin** [comment]
@timdorr  - yes, please, one example.
