### ISSUE TITLE
 Actions may not have an undefined "type" property. Have you misspelled a constant?

### ISSUE THREAD

**Issue by kodermax** [rackt/react-router-redux#238]
![image](https://cloud.githubusercontent.com/assets/590985/12553365/0d8b3ab8-c388-11e5-9b16-2df888fd2f3a.png)

when we calll this dispatch loginUserRequest, i got error 
Uncaught Error: Actions may not have an undefined "type" property. Have you misspelled a constant?

**Comment by timdorr** [comment]
This is a Redux issue, not react-router-redux.

**Comment by Trevoke** [comment]
I wonder what that error message means, too.

**Comment by potapovDim** [comment]
you try to dispatch action what has inside dispatch
