### ISSUE TITLE
listenForReplays API breaking change in 2.1.0

### ISSUE THREAD

**Issue by davezuko** [rackt/react-router-redux#239]
The API for `listenForReplays` changed with https://github.com/rackt/react-router-redux/commit/22db2bb57d6a23661dbd6960864ec29da212a2e1 which was released in the `2.1.0` tag. Unless I'm mistaken, this is a breaking change for any application using this functionality.

Not sure what can be done about it, but wanted to point it out. I can't decide whether or not this should be classified as a breaking change, in the sense that the underlying functionality still works, but it's going to mess up anybody who's relying on the previous state shape.

See https://github.com/davezuko/react-redux-starter-kit/commit/53e7f466662d67c5d9c4b51095d41b68fe619672 as an example.

**Comment by timdorr** [comment]
Technically, this is a breaking change, but we didn't want to suddenly jump to 3.0 over something so minor. Hence, it was made as a minor change. I recommend *not* using caret ranges for your dependencies and instead switching to tilde ranges, as they're more powerful and offer greater control over the modules you're using.

**Comment by davezuko** [comment]
Well, seeing as the rest of redux is following semver it seems crazy to have that _not_ be the case here. If you're not going to bump a major it would be nice to at least get some sort of upgrade path documentation so people don't have to dig through the commit history.

**Comment by SimenB** [comment]
> Technically, this is a breaking change, but we didn't want to suddenly jump to 3.0 over something so minor.

It's just a number though, why not bump it? Ints are cheap. It doesn't have to be changes in the scale of babel 5 -> 6 to be worthy of a major bump.
And as long as npm by default adds `^` the vast majority of your users will have a caret in their package.json.

**Comment by timdorr** [comment]
It's part of a renamed module anyways, so you'll have to muck about with the package.json to get that version anyways. No one is going to be automatically updated to this version.

But you are both right. That's not any excuse. I'll not be so afraid of version numbers in the future. I thought I had learned the lesson on react-router, but apparently not!

**Comment by davezuko** [comment]
@timdorr good point about the package naming change, I considered that and figured that was a reasonable conclusion but wanted to make sure others weren't caught off guard. Oh well, live and learn!
