### ISSUE TITLE
Correct way to deal with async loading of state 

### ISSUE THREAD

**Issue by latkins** [rackt/react-router-redux#240]
What is the correct way to deal with state that must be fetched from a server on a route change? Using react-router's Link component to change the route seems natural, but it isn't clear to me how I should then fire the appropriate action. Or do I have it backwards - fire the action with onClick, and then change the route? I couldn't see any examples showing the best way to do this.

**Comment by timdorr** [comment]
This is a standard React issue. The common and simplest method of dealing with this is to put it in your `componentWillMount` of the component that needs the state data. You can show a loading spinner in the component while it waits on the data to load.

**Comment by latkins** [comment]
Sure. What if I have /foo/1, and load state for this route in
componentWillMount. I then transition to /foo/2, and need to load the state
for 2. The component is already mounted. Should I now use
componentwillreceive props, check the location and dispatch the action? Or
is there some better way?

**Comment by timdorr** [comment]
You should avoid `connect`ing your component to the location state. Use `this.props.params` to get access to that information. You can use the `componentWillReceiveProps` lifecycle method with that safely.
