### ISSUE TITLE
Reload route

### ISSUE THREAD

**Issue by pulpfree** [rackt/react-router-redux#242]
I'm new to react-router and react-router-redux. I'm wondering how to re-load a route once loaded, currently I'm getting 404 status. Here is my render in index.js

    const history = createBrowserHistory()
    const middleware = syncHistory(history)
    const store = configureStore()

    render(
      <Provider store={store}>
        <Router history={history}>
          <Route path="/" component={MainContainer}>
            <IndexRoute component={Dashboard}/>
          </Route>
          <Route path="/admin/" component={Admin}>
          </Route>
        </Router>
      </Provider>,
      document.getElementById('root')
    )

Navigating links works fine, but a reload on the '/admin/' route (or sending a url to someone) doesn't. This was a pretty simple thing and angular-ui and I've seen some comments on Stack using "Router.run" and not clear what best way is and whether I'm should be looking at my webpack config?

Your help is appreciated. BTW, great repo here.

ron

**Comment by timdorr** [comment]
You'll need to set up your server to handle those URLs that don't actually exist on the server. There are many ways of doing this, all depending on what kind of server you have. The main react-router docs have some starting points for how to do it: https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#configuring-your-server
