### ISSUE TITLE
routeActions.push vs history.push

### ISSUE THREAD

**Issue by Dattaya** [rackt/react-router-redux#243]
I'd like to know what is the benefit of using `dispatch(routeActions.push('/foo'))` instead of `react-router`/`browserHistory.push` or `this.context.router.push`? I thought it's because we can pass some additional arguments into the action creator `dispatch(routeActions.push('/foo', {test: 'test'}))` and receive them in reducer `case UPDATE_LOCATION: console.log(action.test);` but that's not the case.

**Comment by timdorr** [comment]
It's so you can track the action via middleware (such as analytics) and respond to those actions _before_ history has a chance to touch them.

Support for more args is being tracked in #187

**Comment by timdorr** [comment]
I think it's implicit that using this library indicates you want to interact with the router using redux as much as possible. There are other benefits, but I think the primary one is good code patterns. I don't think that needs to be stated, but feel free to add a PR if you have something compelling in mind :smile:
