### ISSUE TITLE
Passing on object when switching routes

### ISSUE THREAD

**Issue by aoshi321** [rackt/react-router-redux#245]
Hi

I have a scenario where I have a login page and I want to switch to another path after I have logged in, but at the same time passing on an object to that next page after I've switched routes. What is the best way to accomplish this?

thanks

**Comment by mjrussell** [comment]
@aoshi321 is there some reason that you can store this value in redux first and then pull it on the next page from the store?

An alternative solution could be to use the routerState you can pass to `push` to store it inside the htmlHistory. See https://github.com/rackt/history/blob/master/docs/Glossary.md#locationstate for info on router state

**Comment by aoshi321** [comment]
I have data returned from the server during the login process but as I now want to switch routes Im not sure how I would pass that data onto to the redux state during that process. I looked a this routeState solution before but was wondering if there was a alternative way to do it.

**Comment by timdorr** [comment]
You can store extra data in your location.state when navigating.
