### ISSUE TITLE
Actions for hash based navigation? 

### ISSUE THREAD

**Issue by peteruithoven** [rackt/react-router-redux#247]
I'm trying to use the hash based history, but I can't figure out which actions to use to navigate. 

By basic setup:
``` jsx
  <Provider store={store}>
    <Router history={hashHistory}>
      <Route path="/" component={App}>
        <Route path="save" component={Save}/>
        <Route path="open" component={Open}/>
      </Route>
    </Router>
  </Provider>
```
When I change the url in the url bar to `/#/save` it works, the save and open components show up. 

When I use a react-router Link component like below it works. 
``` jsx
<Link to="save">save</Link>
```

But I don't understand how to use the react-router-redux actions. 
The following code removes the hash and navigates to `/save`: 
``` javascript
dispatch(routeActions.push('save'));
```
The following code moves to `/#/save` (which is what I want) but it doesn't open my components.  
``` javascript
dispatch(routeActions.push('/#/save'));
```

What am I missing here? 

I'm using: 
- react-router: npm:react-router@2.0.0-rc5
- react-router-redux: npm:react-router-redux@2.1.0

**Comment by mjrussell** [comment]
@peteruithoven how are you passing history to `syncHistory`? 

I wonder if you have `browserHistory` in there...

**Comment by peteruithoven** [comment]
Omg, thanks! So many moving parts... 

I indeed still passed browserHistory for syncHistory, changing that to: 
``` javascript
const reduxRouterMiddleware = syncHistory(hashHistory);
```
I can now do a regular push and it all works. 
```
dispatch(routeActions.push('save'));
```

Thanks again for the help, hopefully someone with the same issue stumbles upon this issue.

**Comment by mjrussell** [comment]
:+1: glad it was an easy fix!
