### ISSUE TITLE
2.0 API makes the store depends on the DOM

### ISSUE THREAD

**Issue by geowarin** [rackt/react-router-redux#250]
After upgrading to the 2.0 API, the fact that there is an `historyMiddleware` that takes the history as an argument broke my tests in an unexpected way:

```
Invariant Violation: Browser history needs a DOM
```

I used to be able to initialise the store in my tests without any problem.

The workaround for now is this:

```javascript
import { createHistory, createMemoryHistory } from 'history';
export default process.env.NODE_ENV === 'test' ? createMemoryHistory() : createHistory();
```

Overall, I think I like the new API but this is a bit awkward.

**Comment by timdorr** [comment]
You still had to pass a `history` into the old API. I get this may be awkward with how you've structured, your code, but this comment has a possible way of handling it: https://github.com/rackt/react-router-redux/issues/199#issuecomment-172071740
