### ISSUE TITLE
Query not passed to state when using LocationDescriptorObject in push

### ISSUE THREAD

**Issue by fvzzy** [rackt/react-router-redux#267]
Quite new to this, but I'm trying to rewrite an app which previously used `react-router` using `react-router-redux` and running into some issues.

I'm going from a 

```this.props.dispatch(this.props.pushStateActionCreator(null, this.props.pathname, { query, columns: finalColumns }));```

to

```
this.props.dispatch(routeActions.push({
    pathname: '/f/search/devices',
    query: {
        query,
        columns: finalColumns,
    },
}));
```

where `query = "d1.type='sf' & (d1.status.buildNumber=26878 | d1.status.buildNumber=26995) & d1.status.flavour != 'rs'"` and `finalColumns = ["d1.type", "d1.status.buildNumber", "d1.status.flavour"]`

From what I can tell the URL in the browser isn’t being updated and nothing is returned after submitting a search. I don’t think `query` here is being stored in state either.

Googling around, I've noticed a few people having similar issues - is there a known problem here?

**Comment by timdorr** [comment]
Are you using React Router 1.0 or 2.0?

**Comment by fvzzy** [comment]
`npm ls` for this project gives me `react-router@1.0.3` and `react-router-redux@2.1.0`

**Comment by timdorr** [comment]
Have you tried upgrading to React Router 2.0? It's fully backwards compatible with 1.0.

**Comment by fvzzy** [comment]
Thanks @timdorr - looks like that worked.
