### ISSUE TITLE
Rename to react-router-redux

### ISSUE THREAD

**Issue by jlongster** [rackt/react-router-redux#80]
@ryanflorence and @mjackson have invited this project to join the `rackt` set of projects since it aligns well with how they envision react-router and redux integration. I think it will essentially replace `redux-router` and that will live as its own standalone project.

We're considering renaming it `react-router-redux` as it will be more official bindings. Unless anyone has any better ideas, I say we go with it.

**Comment by ellbee** [comment]
Will be great to have this project join `rackt`!

`react-router-redux` sounds good to me :+1:

**Comment by kjbekkelund** [comment]
That's great! :+1: :100:

**Comment by arkist** [comment]
good enough :star2:

**Comment by lukebennett** [comment]
Definite thumbs up from me :+1:

**Comment by omnidan** [comment]
Sounds good! Just have to make sure it's not too confusing to have two react/redux routers that sound almost the same too. (`redux-router` vs `react-router-redux`) That could be solved with documentation though. (explaining the differences between the two)

**Comment by choonkending** [comment]
I reckon go for it! Sounds exciting.

**Comment by jlongster** [comment]
I'm going to set a date for this: Wednesday. I'll think through anything we need to do before then.

**Comment by jlongster** [comment]
I stalled on this because I was worried about the rename, sync redux-router is also in rackt it seems like calling this react-router-redux is going to be super confusing.

@ryanflorence @mjackson Are you all sure you want to rename this? If so, I feel like we should either rename redux-router or do something so that it's not so confusing which is which.

**Comment by MattKunze** [comment]
Any reason to switch away from *redux-simple-router*? I usually cringe when things have "simple" in the name (argh SOAP!), but it actually seems warranted in this case

**Comment by jlongster** [comment]
I think Ryan and Michael want it to be more "official" bindings. But I suspect with enough community feedback they might be fine keeping the name.

**Comment by gaearon** [comment]
Maybe we can find a different name for `redux-router` too?

**Comment by ryanflorence** [comment]
We're removing the current redux-router from rackt, so there shouldn't be any confusion.

**Comment by ryanflorence** [comment]
@acdlite can you transfer it to your account?

**Comment by acdlite** [comment]
Done! :)

**Comment by acdlite** [comment]
I also added a comment to the README directing people to this repo: https://github.com/acdlite/redux-router#for-a-more-stable-official-binding-between-redux-and-react-router-try-redux-simple-router

**Comment by jlongster** [comment]
Thanks for all your work @acdlite!

**Comment by jlongster** [comment]
I just moved it, but I lost access to any settings. @ryanflorence can you help me figure out permissions? github is so confusing with permissions. How can I maintain admin access, as well as give it to kjbekkelund?

I can't rename the repo until I get access back.

**Comment by satazor** [comment]
`react-router-redux` looks great to me... same as `react-router` but suffixed with redux.. Looking forward to this!

**Comment by naw** [comment]
Correct me if I'm wrong, but `redux-simple-router` just ties `redux` to a `history` object, and isn't actually react-specific.  If so, react probably shouldn't be in the new name.

From a loose coupling perspective, you could imagine using this with a redux-based application without react-router at all (i.e. either a completely different non-react router, or perhaps a different react-specific router), as long as those routers were designed to interact with a `history` object.

**Comment by kjbekkelund** [comment]
@naw Yep, as of right now we're not coupled to `react-router` at all, but we _might_ end up going that route (see #95 — long discussion with lots of thoughts and ideas).

But yeah, either way, I also prefer `redux-simple-router` to `react-router-redux`.

**Comment by ryanflorence** [comment]
"Simple", "smart", or "tiny" always end up being lies or offenses. Eventually, your library becomes complex, surprising, or gigantic. If you're lucky, it simply remains an affront (purposeful or not) to other people's attempts at solving the same problem. I think the new name avoids both problems.

My personal interest in bringing it into Rackt is for an official answer to the question "how should I connect react router and redux?". I'd rather a library be named to answer a question v. explaining the (initial) complexity of implementation :)

**Comment by gaearon** [comment]
What about `redux-history`?

**Comment by kidwm** [comment]
Why not just use `redux-react-router` ?

**Comment by timdorr** [comment]
@jlongster Have you made any decisions on this? Half of this issue was the move to rackt, which is completed. The other half is a rename, which seems to be less pressing (and would nullify the existing "brand" of the project). I'm inclined to say we're done here unless there's a strong desire to rename things.

**Comment by jlongster** [comment]
This project has already evolved to be a little more complex, nothing crazy but I agree with @ryanflorence that the current name isn't very suitable to long-term decisions. Having `simple` made a strong point in the beginning but `react-router-redux` makes more sense.

We probably should have done this with 2.0.0. Why don't we do this in the next few days with a minor release?

**Comment by timdorr** [comment]
Sure, sounds great!

I say at some point in the near future (this weekend?) we push a 2.1.0 release under the new name and then [deprecate 2.0.4](https://docs.npmjs.com/cli/deprecate) under the old name with a warning about the name switch. I also say we keep releasing under both names until 3.0 hits (if ever), deprecating any releases under `redux-simple-router` with that same warning. Sound like a plan?

**Comment by jlongster** [comment]
@timdorr Sounds good, but I don't think we need to keep releasing under both names. I heard from Dan Abramov you can tell npm to redirect it, so `npm install redux-simple-router` still works even if our package is `react-router-redux`. If that works, the biggest pain point goes away (both github and npm will redirect).

I might be remembering wrong... hope not.

**Comment by timdorr** [comment]
It sounds like they can *maybe* do it for us, but it might be delayed or ignored: https://github.com/npm/npm/issues/7515 I think `npm deprecate` is the preferred option for now.

**Comment by gaearon** [comment]
No, I think only GitHub repos can be redirected. With npm you need to deprecate.

**Comment by jlongster** [comment]
Oh, that's right. Isn't there at least a way to tell the user "this is deprecated, you should download react-router-redux instead"? I could have sworn there was, but I'm probably wrong. I'll look into it more today/tomorrow.

I'm not sure I want to keep releasing under both names, that seems like it could be more confusing, and just make people change it to get the new version. It shouldn't be too hard to change names, just find/replace.

**Comment by timdorr** [comment]
Yes, that's what `npm deprecate` does.

**Comment by timdorr** [comment]
We need to push a 2.1.0 for #218 and #225. That would be a good time to do a rename, so I can take care of all of that around the same time, if there are no objections.

**Comment by jlongster** [comment]
Ok, that sounds good.

**Comment by timdorr** [comment]
OK, kicking this off now. I'm going to merge in #218, update the URLs in the project, and then publish that as a 2.1.0 under the `react-router-redux` package on NPM. I'll then `npm deprecate` 2.0.4 and we'll be good to go.

**Comment by timdorr** [comment]
![](http://i.imgur.com/8dvzpYo.gif)
